name: '.NET Build and Test'
description: 'A GitHub Action to build and test .NET applications'
author: 'Yash Mahi'
branding:
  icon: 'check-circle' 
  color: 'blue'

inputs:
  dotnet-version:
    description: 'The version of .NET SDK to use'
    required: true
    default: '8.0.x'

outputs:
  build-status:
    description: 'The status of the build process'

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build --configuration Release

    - name: Run Tests
      run: dotnet test

    - name: Set Output
      id: build-status
      run: echo "::set-output name=build-status::success"
